stages:
  - mavenbuild
  - maventest
  - androidtry

maven-build:
  stage: mavenbuild
  tags:
    - springboot_tag
  script:
    - cd Backend/Splask 
    - mvn package
maven-test:
  stage: maventest
  tags:
    - springboot_tag
  script: 
    - cd Backend/Splask
    - mvn test
  artifacts:
    paths:
      - Backend/target/*.jar

android-build:
  image: gjandres/android-ci:latest
  stage: androidtry
  tags:
    - android_tag
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
  script:
    - cd Frontend
    - ./gradlew assemble
