stages:
  - maventry
  - androidtry

maven-build:
  stage: maventry
  tags:
    - springboot_tag
  script:
    - cd Backend/Splask 
    - mvn package

android-build:
  image: alpine:latest
  stage: androidtry
  tags:
    - android_tag
  before_script:
    - export GRADLE_USER_HOME-'pwd'/.gradle
    - chmod +x ./Frontend/gradlew
  script:
    - cd Frontend/app
    - ./gradlew assemble